name: SaGe Test server
maintainer: Shi Zue
quota: 500
max_results: 2000
graphs:
-
  name: bsbm
  uri: http://example.org/graph
  description: DefinitelyAUsefulDescription
  backend: hdt-file
  file: /media/theray1/Files/Files/data/wdbench.hdt
